modLoader="javafml"
loaderVersion="[36,)"
license="Apache-2.0"

[[mods]]
modId="compatoplenty"
authors = "Selene and Mana"
version="${file.jarVersion}"
displayName="Compat O' Plenty"
logoFile="logo.png"
description='''
A mod designed to fill the gap in content between Biomes O' Plenty and Quark, Farmer's Delight, and Buzzier Bees.
'''

[[dependencies.compatoplenty]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compatoplenty]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.16.5-3.3.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.compatoplenty]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.16.5-13.1.0.477,)"
    ordering="AFTER"
    side="BOTH"