modLoader="javafml"
loaderVersion="[43,)"
license="Apache-2.0"

[[mods]]
modId="compatoplenty"
authors = "Selene and Mana"
version="${file.jarVersion}"
displayName="Compat O' Plenty"
logoFile="logo.png"
description='''
A mod designed to fill the gap in content between Biomes O' Plenty and Quark, Farmer's Delight, and Buzzier Bees.
'''

[[dependencies.compatoplenty]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compatoplenty]]
    modId="blueprint"
    mandatory=true
    versionRange="[1.19.2-6.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.compatoplenty]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.19.2-17.1.1.163,)"
    ordering="AFTER"
    side="BOTH"
