modLoader="javafml"
loaderVersion="[39,)"
license="Apache-2.0"

[[mods]]
modId="compatoplenty"
authors = "Selene and Mana"
version="${file.jarVersion}"
displayName="Compat O' Plenty"
logoFile="logo.png"
description='''
A mod designed to fill the gap in content between Biomes O' Plenty and Quark, Farmer's Delight, and Buzzier Bees.
'''

[[dependencies.compatoplenty]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compatoplenty]]
    modId="blueprint"
    mandatory=true
    versionRange="[1.18.1-5.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.compatoplenty]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.18.1-15.0.0.94,)"
    ordering="AFTER"
    side="BOTH"
